### ISSUE TITLE
openwrt official 23.05 error 

### ISSUE THREAD

**Issue by GWan1234** [lucikap/luci-app-nettask#4]
OpenWrt 23.05-SNAPSHOT r23904-f12cf43029 / LuCI openwrt-23.05 branch git-24.180.72161-85dec60

Runtime error
Unhandled exception during request dispatching
/usr/lib/lua/luci/ucodebridge.lua:14: /usr/lib/lua/luci/model/cbi/trontabs.lua:1: module 'luci.fs' not found:
no field package.preload['luci.fs']
no file './luci/fs.lua'
no file '/usr/share/lua/luci/fs.lua'
no file '/usr/share/lua/luci/fs/init.lua'
no file '/usr/lib/lua/luci/fs.lua'
no file '/usr/lib/lua/luci/fs/init.lua'
no file './luci/fs.so'
no file '/usr/lib/lua/luci/fs.so'
no file '/usr/lib/lua/loadall.so'
no file './luci.so'
no file '/usr/lib/lua/luci.so'
no file '/usr/lib/lua/loadall.so'

In h(), file [C]
called from function [anonymous function] (/usr/lib/lua/luci/ucodebridge.lua:14)
called from function ((tail call))
In [anonymous function](), file /usr/share/ucode/luci/runtime.uc, line 148, byte 45:
  called from function [arrow function] (/usr/share/ucode/luci/dispatcher.uc:794:4)
  called from function render ([C])
  called from function render_action (/usr/share/ucode/luci/dispatcher.uc:768:24)
  called from function run_action (/usr/share/ucode/luci/dispatcher.uc:795:4)
  called from function [anonymous function] (/usr/share/ucode/luci/dispatcher.uc:1003:48)
  called from anonymous function (/www/cgi-bin/luci:39:13)

 `        return lcall.call(modname, method, ...args);`
  Near here ----------------------------------------^

**Comment by lucikap** [comment]
> OpenWrt 23.05-快照 r23904-f12cf43029 / LuCI openwrt-23.05 分支 git-24.180.72161-85dec60
> 
> 运行时错误 请求调度期间未处理的异常 /usr/lib/lua/luci/ucodebridge.lua：14： /usr/lib/lua/luci/model/cbi/trontabs.lua：1： 找不到模块“luci.fs”： 没有字段 package.preload['luci.fs'] 没有文件 './luci/fs.lua' 没有文件 '/usr/share/lua/luci/fs.lua' 没有文件 '/usr/share/lua/luci/fs/init.lua' 没有文件 '/usr/lib/lua/luci/fs.lua' 没有文件 '/usr/lib/lua/luci/fs/init.lua'没有文件 './luci/fs.so' 没有文件 '/usr/lib/lua/luci/fs.so' 没有文件 '/usr/lib/lua/loadall.so' 没有文件 './luci.so' 没有文件 '/usr/lib/lua/luci.so' 没有文件 '/usr/lib/lua/loadall.so'
> 
> 在 h（） 中，从函数 [匿名函数] （/usr/lib/lua/luci/ucodebridge.lua：14） 调用的文件 [C] 从函数调用 （（tail call）） 在匿名函数中，文件 /usr/share/ucode/luci/runtime.uc，第 148 行，字节 45：从函数 [arrow function] （/usr/share/ucode/luci/dispatcher.uc：794：4） 调用 从函数 render_action render （[C]） 调用 （/usr/share/ucode/luci/dispatcher.uc：768：24）从函数 run_action 调用 （/usr/share/ucode/luci/dispatcher.uc：795：4） 从函数 [匿名函数] （/usr/share/ucode/luci/dispatcher.uc：1003：48） 调用 从匿名函数 （/www/cgi-bin/luci：39：13） 调用
> 
> ` return lcall.call(modname, method, ...args);`靠近这里 ----------------------------------------^

官方的18以上的luci会出现这个问题，新的luci中不支持一些老的控件，有空我做一个兼容的
